/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./*.{js,jsx}",
    "./components/**/*.{js,jsx}",
    "./hooks/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#303030",
        /** Named `muted-line` (not `outline`) to avoid clashing with Tailwind’s `outline` utilities */
        "muted-line": "#978da1",
        "surface-container-low": "#1b1b1b",
        "on-tertiary-fixed": "#1b1b1b",
        "surface-container-high": "#2a2a2a",
        "on-background": "#e2e2e2",
        "primary-fixed": "#eddcff",
        "on-surface": "#e2e2e2",
        "on-secondary-container": "#00653b",
        "on-primary-fixed": "#290055",
        "on-tertiary-fixed-variant": "#474747",
        "surface-variant": "#353535",
        "primary-fixed-dim": "#d8b9ff",
        "tertiary-fixed": "#e2e2e2",
        "on-surface-variant": "#cec2d8",
        "inverse-surface": "#e2e2e2",
        tertiary: "#c6c6c6",
        "surface-tint": "#d8b9ff",
        "surface-container-lowest": "#0e0e0e",
        "primary-container": "#9945ff",
        surface: "#131313",
        "on-primary-fixed-variant": "#6300bb",
        secondary: "#a0ffc3",
        primary: "#d8b9ff",
        "on-tertiary-container": "#ffffff",
        error: "#ffb4ab",
        "on-error": "#690005",
        "surface-container-highest": "#353535",
        "on-secondary-fixed": "#002110",
        background: "#131313",
        "secondary-container": "#00ec91",
        "on-primary-container": "#ffffff",
        "surface-dim": "#131313",
        "secondary-fixed": "#56ffa8",
        "inverse-primary": "#7f21e5",
        "surface-container": "#1f1f1f",
        "on-tertiary": "#303030",
        "tertiary-fixed-dim": "#c6c6c6",
        "tertiary-container": "#767676",
        "on-primary": "#450086",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "on-secondary": "#00391f",
        "outline-variant": "#4c4355",
        "surface-bright": "#393939",
        "secondary-fixed-dim": "#00e38b",
        "on-secondary-fixed-variant": "#00522f",
      },
      borderRadius: {
        DEFAULT: "0rem",
        lg: "0rem",
        xl: "0rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
    },
  },
  plugins: [],
};
