const C = {
  bg:        "#1a1a1e",
  surface:   "#252529",
  surface2:  "#2e2e33",
  border:    "#3a3a40",
  cyan:      "#00d4aa",
  green:     "#20c997",
  red:       "#ff4d6a",
  text:      "#e8e8ea",
  dim:       "#7a7a80",
  muted:     "#5a5a60",
  inputBg:   "#303036",
  hover:     "#3a3a44",
  accent:    "#6c5ce7",
};
const mono = "'SF Mono','Cascadia Code','Fira Code',monospace";

const S = {
  shell:     { display:"flex", height:"100vh", fontFamily:mono, background:C.bg, color:C.text, overflow:"hidden" },
  sidebar:   { width:280, minWidth:280, background:"#121215", borderRight:`1px solid ${C.border}`, display:"flex", flexDirection:"column", overflow:"hidden" },
  sideHead:  { padding:"16px 16px 12px", display:"flex", alignItems:"center", justifyContent:"space-between" },
  sideTitle: { fontSize:10, letterSpacing:"0.14em", color:C.dim, textTransform:"uppercase", fontWeight:700 },
  newChat:   { background:C.cyan, border:"none", borderRadius:6, color:"#111", fontFamily:mono, fontSize:10, fontWeight:800, padding:"8px 14px", cursor:"pointer", letterSpacing:"0.06em", transition:"all 0.15s" },
  sideScroll:{ flex:1, overflowY:"auto", padding:"4px 0" },
  histItem:  (active, ok) => ({ padding:"10px 16px", cursor:"pointer", background: active ? "#1a1a20" : "transparent", borderLeft:`3px solid ${active ? C.cyan : "transparent"}`, borderBottom:`1px solid ${C.border}22`, opacity: ok ? 1 : 0.5, transition:"background 0.1s" }),
  histStrat: { fontSize:11, color:C.text, marginBottom:4, whiteSpace:"nowrap", overflow:"hidden", textOverflow:"ellipsis", lineHeight:1.4 },
  histMeta:  { display:"flex", gap:8, alignItems:"center", fontSize:10 },
  badge:     (ok) => ({ padding:"2px 7px", borderRadius:4, background: ok ? "#0a2e1a" : "#2a1012", color: ok ? C.green : C.red, border:`1px solid ${ok ? "#135228" : "#5a1a1a"}`, fontSize:8, fontWeight:700, letterSpacing:"0.04em" }),
  retVal:    (v) => ({ fontSize:11, fontWeight:700, color: v > 0 ? C.green : v < 0 ? C.red : C.dim, fontFamily:mono }),
  histDate:  { fontSize:9, color:C.muted },
  delBtn:    { background:"none", border:"none", color:C.dim, cursor:"pointer", fontSize:13, padding:"0 3px", marginLeft:"auto", lineHeight:1, opacity:0.4, transition:"opacity 0.15s" },
  sideEmpty: { padding:32, textAlign:"center", fontSize:10, color:C.dim, lineHeight:1.8 },
  statsBox:  { borderTop:`1px solid ${C.border}`, padding:"12px 16px", display:"flex", flexDirection:"column", gap:6, background:"#121215" },
  statRow:   { display:"flex", justifyContent:"space-between", fontSize:9, color:C.dim },
  statVal:   { color:C.text, fontWeight:700 },
  main:      { flex:1, display:"flex", flexDirection:"column", overflow:"hidden", background:C.bg },
  topBar:    { padding:"10px 24px", display:"flex", alignItems:"center", justifyContent:"space-between", borderBottom:`1px solid ${C.border}44`, flexShrink:0 },
  topTitle:  { fontSize:14, color:C.text, fontWeight:700, letterSpacing:"-0.02em", display:"flex", alignItems:"center", gap:8 },
  topSub:    { fontSize:10, color:C.dim, marginLeft:8 },
  toggleWrap:{ display:"flex", alignItems:"center", gap:2, background:"#121215", borderRadius:6, padding:2, border:`1px solid ${C.border}55` },
  toggleBtn: (active) => ({ background: active ? C.cyan : "transparent", border:"none", borderRadius:4, color: active ? "#111" : C.dim, fontFamily:mono, fontSize:10, fontWeight:700, padding:"5px 12px", cursor:"pointer", transition:"all 0.15s", letterSpacing:"0.02em" }),
  pills:     { padding:"10px 24px 4px", display:"flex", gap:8, flexWrap:"wrap", flexShrink:0 },
  pill:      { background:C.surface, border:`1px solid ${C.border}`, borderRadius:20, color:C.dim, fontSize:10, padding:"5px 14px", cursor:"pointer", fontFamily:mono, transition:"all 0.15s", letterSpacing:"0.02em" },
  chatWrap:  { flex:1, overflowY:"auto", display:"flex", flexDirection:"column" },
  chatInner: { maxWidth:860, width:"100%", margin:"0 auto", padding:"20px 24px 12px", display:"flex", flexDirection:"column", gap:0, flex:1 },
  msgUser:   { alignSelf:"flex-end", background:"#2a2d35", borderRadius:"16px 16px 4px 16px", padding:"10px 16px", maxWidth:"70%", fontSize:12, color:C.text, lineHeight:1.6, margin:"6px 0" },
  msgBot:    { alignSelf:"flex-start", width:"100%", maxWidth:860, padding:"4px 0", fontSize:12, lineHeight:1.7, color:C.text },
  msgText:   { padding:"10px 0", fontSize:12, lineHeight:1.7, color:"#c8c8d0" },
  errBox:    { background:"#2a1014", borderLeft:"3px solid #5a1a1a", borderRadius:"0 6px 6px 0", padding:"10px 14px", fontSize:11, color:C.red, marginTop:8 },
  tag:       { display:"inline-block", background:"#0a2e1a", border:"1px solid #135228", borderRadius:4, padding:"2px 8px", fontSize:9, color:C.green, marginBottom:10, letterSpacing:"0.1em", fontWeight:700 },
  mGrid:     { display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(110px,1fr))", gap:8, margin:"10px 0" },
  mCard:     { background:C.surface, border:`1px solid ${C.border}55`, borderRadius:8, padding:"10px 14px" },
  mLabel:    { fontSize:7, color:C.dim, letterSpacing:"0.12em", textTransform:"uppercase", fontWeight:700, marginBottom:4 },
  mVal:      (pos) => ({ fontSize:18, fontWeight:700, color: pos ? C.green : pos === 0 ? C.dim : C.red }),
  chartWrap: { margin:"10px 0", height:180, background:C.surface, borderRadius:8, padding:12, border:`1px solid ${C.border}44` },
  codeBtn:   { background:"none", border:`1px solid ${C.border}`, borderRadius:6, fontFamily:mono, fontSize:10, color:C.dim, cursor:"pointer", padding:"6px 14px", marginTop:8, transition:"all 0.15s" },
  codeBlock: { background:"#121215", border:`1px solid ${C.border}44`, borderRadius:6, padding:12, fontSize:10, color:"#7a7a80", overflowX:"auto", marginTop:8, maxHeight:200, overflowY:"auto", whiteSpace:"pre", lineHeight:1.5 },
  inputWrap: { flexShrink:0, padding:"14px 24px 18px", background:`linear-gradient(transparent, ${C.bg} 20%)` },
  inputInner:{ maxWidth:860, margin:"0 auto", width:"100%" },
  inputRow:  { display:"flex", gap:10, alignItems:"flex-end", background:C.inputBg, borderRadius:12, padding:"8px 14px", border:`1px solid ${C.border}55`, boxShadow:"0 2px 16px rgba(0,0,0,0.3)" },
  textarea:  { flex:1, background:"transparent", border:"none", color:C.text, fontFamily:mono, fontSize:12, padding:"6px 4px", resize:"none", outline:"none", lineHeight:1.5, minHeight:20, maxHeight:120 },
  runBtn:    { background:"linear-gradient(135deg, #00d4aa, #00b894)", border:"none", borderRadius:8, color:"#111", fontFamily:mono, fontSize:11, fontWeight:800, padding:"8px 18px", cursor:"pointer", whiteSpace:"nowrap", transition:"all 0.15s", letterSpacing:"0.06em" },
  runBtnD:   { opacity:0.35, cursor:"not-allowed" },
  loader:    { display:"flex", alignItems:"center", gap:8, padding:"10px 0", fontSize:11, color:C.dim },
  // Admin
  loginWrap:  { display:"flex", alignItems:"center", justifyContent:"center", height:"100%", background:C.bg },
  loginBox:   { background:"#121215", border:`1px solid ${C.border}`, borderRadius:12, padding:"48px 40px", width:400, boxShadow:"0 8px 40px rgba(0,0,0,0.6)" },
  loginTitle:{ fontSize:20, fontWeight:700, color:C.text, marginBottom:8, textAlign:"center" },
  loginSub:  { fontSize:11, color:C.dim, textAlign:"center", marginBottom:32 },
  loginField:{ width:"100%", background:C.inputBg, border:`1px solid ${C.border}55`, borderRadius:8, padding:"10px 14px", color:C.text, fontFamily:mono, fontSize:12, outline:"none", marginBottom:16, boxSizing:"border-box" },
  loginBtn:  { width:"100%", background:"linear-gradient(135deg, #00d4aa, #00b894)", border:"none", borderRadius:8, color:"#111", fontFamily:mono, fontSize:12, fontWeight:700, padding:"12px", cursor:"pointer", letterSpacing:"0.06em", transition:"all 0.15s" },
  loginErr:  { color:C.red, fontSize:10, marginBottom:12, textAlign:"center" },
  adminWrap: { flex:1, overflowY:"auto", padding:"24px 32px" },
  adminInner:{ maxWidth:1200, width:"100%", margin:"0 auto" },
  adminTitle:{ fontSize:20, fontWeight:700, color:C.text, marginBottom:4 },
  adminSub:  { fontSize:11, color:C.dim, marginBottom:24 },
  adminCard: { background:"#121215", border:`1px solid ${C.border}`, borderRadius:10, padding:"20px", marginBottom:20 },
  adminCardTitle:{ fontSize:14, fontWeight:700, color:C.text, marginBottom:16, display:"flex", alignItems:"center", gap:8 },
  tableWrap: { overflowX:"auto", marginTop:12 },
  table:     { width:"100%", borderCollapse:"collapse", fontSize:11, color:C.text },
  th:        { padding:"10px 12px", textAlign:"left", borderBottom:`2px solid ${C.border}`, color:C.dim, fontSize:8, textTransform:"uppercase", letterSpacing:"0.12em", fontWeight:700 },
  td:        { padding:"10px 12px", borderBottom:`1px solid ${C.border}22`, fontSize:11 },
  tdGreen:  { color:C.green, fontWeight:600 },
  tdRed:    { color:C.red, fontWeight:600 },
  tdMuted:  { color:C.dim },
  badge2:    (ok) => ({ display:"inline-block", padding:"2px 8px", borderRadius:4, background: ok ? "#0a2e1a" : "#2a1012", color: ok ? C.green : C.red, border:`1px solid ${ok ? "#135228" : "#5a1a1a"}`, fontSize:8, fontWeight:700 }),
  statsGrid: { display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))", gap:16, marginBottom:24 },
  statCard:  { background:"#121215", border:`1px solid ${C.border}`, borderRadius:10, padding:"20px", textAlign:"center" },
  statNum:   { fontSize:28, fontWeight:700, color:C.cyan, margin:"8px 0" },
  statLabel: { fontSize:8, color:C.dim, textTransform:"uppercase", letterSpacing:"0.12em", fontWeight:700 },
  logoutBtn: { background:"none", border:`1px solid ${C.border}`, borderRadius:6, color:C.dim, fontFamily:mono, fontSize:10, padding:"6px 14px", cursor:"pointer", transition:"all 0.15s" },
  tabWrap:   { display:"flex", gap:2, background:"#121215", borderRadius:8, padding:3, border:`1px solid ${C.border}55`, marginBottom:24 },
  tabBtn:    (active) => ({ background: active ? C.cyan : "transparent", border:"none", borderRadius:6, color: active ? "#111" : C.dim, fontFamily:mono, fontSize:11, fontWeight:600, padding:"8px 20px", cursor:"pointer", transition:"all 0.15s" }),
  delBtn2:   { background:"none", border:`1px solid ${C.red}55`, borderRadius:4, color:C.red, fontFamily:mono, fontSize:9, padding:"4px 10px", cursor:"pointer", opacity:0.6, transition:"all 0.15s" },
};

export { C, S, mono };