const C = {
  bg:        "#0d0d10",
  surface:   "#1a1a1f",
  surface2:  "#24242a",
  surface3:  "#2d2d35",
  border:    "#3a3a42",
  borderLight:"#4a4a52",
  cyan:      "#00d9b0",
  cyanDim:   "#00d9b066",
  green:     "#2ee6b8",
  greenDim:  "#2ee6b833",
  red:       "#ff5c7a",
  redDim:    "#ff5c7a33",
  text:      "#f0f0f2",
  textSec:   "#c8c8d0",
  dim:       "#8a8a92",
  muted:     "#5a5a65",
  inputBg:   "#16161a",
  hover:     "#2a2a32",
  accent:    "#7c6cf7",
  purple:    "#a78bfa",
  yellow:    "#fbbf24",
};
const mono = "'SF Mono','Fira Code','Cascadia Code','JetBrains Mono',monospace";
const sans = "Inter, system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif";

const S = {
  shell:     { display:"flex", height:"100vh", fontFamily:mono, background:`radial-gradient(ellipse at top, #1a1a24 0%, ${C.bg} 40%)`, color:C.text, overflow:"hidden" },
  sidebar:   { width:300, minWidth:300, background:`linear-gradient(180deg, #0f0f14 0%, #0d0d12 100%)`, borderRight:`1px solid ${C.border}`, display:"flex", flexDirection:"column", overflow:"hidden", boxShadow:"4px 0 24px rgba(0,0,0,0.3)" },
  sideHead:  { padding:"20px 18px 16px", display:"flex", alignItems:"center", justifyContent:"space-between" },
  sideTitle: { fontSize:9, letterSpacing:"0.18em", color:C.dim, textTransform:"uppercase", fontWeight:800 },
  newChat:   { background:`linear-gradient(135deg, ${C.cyan}, #00c9a0)`, border:"none", borderRadius:8, color:"#0d0d10", fontFamily:mono, fontSize:10, fontWeight:800, padding:"9px 16px", cursor:"pointer", letterSpacing:"0.06em", transition:"all 0.2s ease", boxShadow:`0 2px 12px ${C.cyanDim}` },
  sideScroll:{ flex:1, overflowY:"auto", padding:"6px 0" },
  histItem:  (active, ok) => ({ padding:"12px 18px", cursor:"pointer", background: active ? `linear-gradient(90deg, ${C.surface} 0%, transparent 100%)` : "transparent", borderLeft:`3px solid ${active ? C.cyan : "transparent"}`, borderBottom:`1px solid ${C.border}1a`, opacity: ok ? 1 : 0.55, transition:"all 0.18s ease" }),
  histStrat: { fontSize:11, color:C.textSec, marginBottom:5, whiteSpace:"nowrap", overflow:"hidden", textOverflow:"ellipsis", lineHeight:1.45, fontWeight:500 },
  histMeta:  { display:"flex", gap:8, alignItems:"center", fontSize:10 },
  badge:     (ok) => ({ padding:"3px 8px", borderRadius:5, background: ok ? C.greenDim : "#2a1014aa", color: ok ? C.green : C.red, border:`1px solid ${ok ? C.greenDim : "#5a1a1aaa"}`, fontSize:8, fontWeight:700, letterSpacing:"0.06em" }),
  retVal:    (v) => ({ fontSize:11, fontWeight:700, color: v > 0 ? C.green : v < 0 ? C.red : C.dim, fontFamily:mono }),
  histDate:  { fontSize:9, color:C.muted },
  delBtn:    { background:"none", border:"none", color:C.dim, cursor:"pointer", fontSize:14, padding:"0 4px", marginLeft:"auto", lineHeight:1, opacity:0.35, transition:"all 0.15s" },
  sideEmpty: { padding:40, textAlign:"center", fontSize:10, color:C.dim, lineHeight:1.9 },
  statsBox:  { borderTop:`1px solid ${C.border}`, padding:"16px 18px", display:"flex", flexDirection:"column", gap:8, background:`linear-gradient(180deg, #0f0f14 0%, #0d0d12 100%)` },
  statRow:   { display:"flex", justifyContent:"space-between", fontSize:9, color:C.dim },
  statVal:   { color:C.textSec, fontWeight:700 },
  main:      { flex:1, display:"flex", flexDirection:"column", overflow:"hidden", background:C.bg },
  topBar:    { padding:"14px 28px", display:"flex", alignItems:"center", justifyContent:"space-between", borderBottom:`1px solid ${C.border}33`, flexShrink:0, background:`linear-gradient(180deg, ${C.surface} 0%, transparent 100%)` },
  topTitle:  { fontSize:15, color:C.text, fontWeight:800, letterSpacing:"-0.02em", display:"flex", alignItems:"center", gap:9 },
  topSub:    { fontSize:10, color:C.dim, marginLeft:8, fontWeight:400 },
  toggleWrap:{ display:"flex", alignItems:"center", gap:2, background:C.inputBg, borderRadius:8, padding:3, border:`1px solid ${C.border}66`, boxShadow:"0 2px 8px rgba(0,0,0,0.2)" },
  toggleBtn: (active) => ({ background: active ? `linear-gradient(135deg, ${C.cyan}, #00c9a0)` : "transparent", border:"none", borderRadius:6, color: active ? "#0d0d10" : C.dim, fontFamily:mono, fontSize:10, fontWeight:700, padding:"6px 14px", cursor:"pointer", transition:"all 0.18s", letterSpacing:"0.02em" }),
  pills:     { padding:"12px 28px 6px", display:"flex", gap:8, flexWrap:"wrap", flexShrink:0 },
  pill:      { background:C.surface, border:`1px solid ${C.border}66`, borderRadius:20, color:C.dim, fontSize:10, padding:"6px 16px", cursor:"pointer", fontFamily:mono, transition:"all 0.18s", letterSpacing:"0.02em", boxShadow:"0 1px 4px rgba(0,0,0,0.15)" },
  chatWrap:  { flex:1, overflowY:"auto", display:"flex", flexDirection:"column" },
  chatInner: { maxWidth:900, width:"100%", margin:"0 auto", padding:"24px 28px 16px", display:"flex", flexDirection:"column", gap:0, flex:1 },
  msgUser:   { alignSelf:"flex-end", background:`linear-gradient(135deg, ${C.surface3}, ${C.surface2})`, borderRadius:"18px 18px 5px 18px", padding:"12px 18px", maxWidth:"72%", fontSize:12, color:C.text, lineHeight:1.65, margin:"8px 0", boxShadow:"0 2px 12px rgba(0,0,0,0.25)", border:`1px solid ${C.border}44` },
  msgBot:    { alignSelf:"flex-start", width:"100%", maxWidth:900, padding:"6px 0", fontSize:12, lineHeight:1.7, color:C.text },
  msgText:   { padding:"12px 0", fontSize:12, lineHeight:1.75, color:C.textSec },
  errBox:    { background:"#2a1014aa", borderLeft:`3px solid ${C.red}`, borderRadius:"0 8px 8px 0", padding:"12px 16px", fontSize:11, color:C.red, marginTop:10, boxShadow:"0 2px 12px rgba(255,92,122,0.1)" },
  tag:       { display:"inline-block", background:C.greenDim, border:`1px solid ${C.greenDim}`, borderRadius:6, padding:"3px 10px", fontSize:9, color:C.green, marginBottom:12, letterSpacing:"0.12em", fontWeight:700 },
  mGrid:     { display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(120px,1fr))", gap:10, margin:"12px 0" },
  mCard:     { background:`linear-gradient(135deg, ${C.surface}, ${C.surface2})`, border:`1px solid ${C.border}66`, borderRadius:10, padding:"14px 16px", boxShadow:"0 2px 12px rgba(0,0,0,0.2)" },
  mLabel:    { fontSize:7, color:C.dim, letterSpacing:"0.14em", textTransform:"uppercase", fontWeight:700, marginBottom:6 },
  mVal:      (pos) => ({ fontSize:20, fontWeight:800, color: pos ? C.green : pos === 0 ? C.dim : C.red, textShadow: pos ? `0 0 20px ${C.greenDim}` : "none" }),
  chartWrap: { margin:"12px 0", height:200, background:`linear-gradient(180deg, ${C.surface}, ${C.surface2})`, borderRadius:10, padding:14, border:`1px solid ${C.border}44`, boxShadow:"0 2px 16px rgba(0,0,0,0.25)" },
  codeBtn:   { background:"none", border:`1px solid ${C.border}66`, borderRadius:8, fontFamily:mono, fontSize:10, color:C.dim, cursor:"pointer", padding:"7px 16px", marginTop:10, transition:"all 0.18s" },
  codeBlock: { background:"#0d0d12", border:`1px solid ${C.border}33`, borderRadius:8, padding:14, fontSize:10, color:C.dim, overflowX:"auto", marginTop:10, maxHeight:240, overflowY:"auto", whiteSpace:"pre", lineHeight:1.55, boxShadow:"inset 0 2px 12px rgba(0,0,0,0.3)" },
  inputWrap: { flexShrink:0, padding:"16px 28px 22px", background:`linear-gradient(transparent, ${C.bg} 10%)` },
  inputInner:{ maxWidth:900, margin:"0 auto", width:"100%" },
  inputRow:  { display:"flex", gap:12, alignItems:"flex-end", background:C.inputBg, borderRadius:14, padding:"10px 16px", border:`1px solid ${C.border}66`, boxShadow:`0 4px 24px rgba(0,0,0,0.35), 0 0 0 1px ${C.cyanDim}11` },
  textarea:  { flex:1, background:"transparent", border:"none", color:C.text, fontFamily:mono, fontSize:12, padding:"8px 6px", resize:"none", outline:"none", lineHeight:1.5, minHeight:22, maxHeight:140 },
  runBtn:    { background:`linear-gradient(135deg, ${C.cyan}, #00c9a0)`, border:"none", borderRadius:10, color:"#0d0d10", fontFamily:mono, fontSize:11, fontWeight:800, padding:"10px 22px", cursor:"pointer", whiteSpace:"nowrap", transition:"all 0.2s", letterSpacing:"0.06em", boxShadow:`0 3px 16px ${C.cyanDim}` },
  runBtnD:   { opacity:0.35, cursor:"not-allowed", boxShadow:"none" },
  loader:    { display:"flex", alignItems:"center", gap:10, padding:"12px 0", fontSize:11, color:C.dim },
  // Admin
  loginWrap:  { display:"flex", alignItems:"center", justifyContent:"center", height:"100%", background:`radial-gradient(ellipse at top, #1a1a24 0%, ${C.bg} 40%)` },
  loginBox:   { background:`linear-gradient(180deg, ${C.surface}, ${C.surface2})`, border:`1px solid ${C.border}66`, borderRadius:14, padding:"52px 44px", width:420, boxShadow:`0 12px 60px rgba(0,0,0,0.5), 0 0 0 1px ${C.cyanDim}11` },
  loginTitle:{ fontSize:22, fontWeight:800, color:C.text, marginBottom:10, textAlign:"center" },
  loginSub:  { fontSize:11, color:C.dim, textAlign:"center", marginBottom:36 },
  loginField:{ width:"100%", background:C.inputBg, border:`1px solid ${C.border}66`, borderRadius:10, padding:"12px 16px", color:C.textSec, fontFamily:mono, fontSize:12, outline:"none", marginBottom:18, boxSizing:"border-box", transition:"border-color 0.18s" },
  loginBtn:  { width:"100%", background:`linear-gradient(135deg, ${C.cyan}, #00c9a0)`, border:"none", borderRadius:10, color:"#0d0d10", fontFamily:mono, fontSize:12, fontWeight:800, padding:"14px", cursor:"pointer", letterSpacing:"0.06em", transition:"all 0.2s", boxShadow:`0 3px 16px ${C.cyanDim}` },
  loginErr:  { color:C.red, fontSize:10, marginBottom:14, textAlign:"center", background:C.redDim, padding:"8px 12px", borderRadius:8 },
  adminWrap: { flex:1, overflowY:"auto", padding:"28px 36px", background:`radial-gradient(ellipse at top, #1a1a24 0%, ${C.bg} 30%)` },
  adminInner:{ maxWidth:1280, width:"100%", margin:"0 auto" },
  adminTitle:{ fontSize:22, fontWeight:800, color:C.text, marginBottom:6 },
  adminSub:  { fontSize:11, color:C.dim, marginBottom:28 },
  adminCard: { background:`linear-gradient(180deg, ${C.surface}, ${C.surface2})`, border:`1px solid ${C.border}66`, borderRadius:12, padding:"22px", marginBottom:22, boxShadow:"0 2px 16px rgba(0,0,0,0.2)" },
  adminCardTitle:{ fontSize:14, fontWeight:700, color:C.text, marginBottom:18, display:"flex", alignItems:"center", gap:8 },
  tableWrap: { overflowX:"auto", marginTop:14, borderRadius:10, border:`1px solid ${C.border}33` },
  table:     { width:"100%", borderCollapse:"collapse", fontSize:11, color:C.textSec },
  th:        { padding:"12px 14px", textAlign:"left", borderBottom:`2px solid ${C.border}`, color:C.dim, fontSize:8, textTransform:"uppercase", letterSpacing:"0.14em", fontWeight:700 },
  td:        { padding:"12px 14px", borderBottom:`1px solid ${C.border}22`, fontSize:11 },
  tdGreen:  { color:C.green, fontWeight:600 },
  tdRed:    { color:C.red, fontWeight:600 },
  tdMuted:  { color:C.dim },
  badge2:    (ok) => ({ display:"inline-block", padding:"3px 9px", borderRadius:5, background: ok ? C.greenDim : "#2a1014aa", color: ok ? C.green : C.red, border:`1px solid ${ok ? C.greenDim : "#5a1a1aaa"}`, fontSize:8, fontWeight:700 }),
  statsGrid: { display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))", gap:18, marginBottom:26 },
  statCard:  { background:`linear-gradient(180deg, ${C.surface}, ${C.surface2})`, border:`1px solid ${C.border}66`, borderRadius:12, padding:"24px", textAlign:"center", boxShadow:"0 2px 16px rgba(0,0,0,0.2)" },
  statNum:   { fontSize:30, fontWeight:800, color:C.cyan, margin:"10px 0", textShadow:`0 0 24px ${C.cyanDim}` },
  statLabel: { fontSize:8, color:C.dim, textTransform:"uppercase", letterSpacing:"0.14em", fontWeight:700 },
  logoutBtn: { background:"none", border:`1px solid ${C.border}66`, borderRadius:8, color:C.dim, fontFamily:mono, fontSize:10, padding:"7px 16px", cursor:"pointer", transition:"all 0.18s" },
  tabWrap:   { display:"flex", gap:2, background:C.inputBg, borderRadius:10, padding:4, border:`1px solid ${C.border}66`, marginBottom:26, boxShadow:"0 2px 8px rgba(0,0,0,0.15)" },
  tabBtn:    (active) => ({ background: active ? `linear-gradient(135deg, ${C.cyan}, #00c9a0)` : "transparent", border:"none", borderRadius:8, color: active ? "#0d0d10" : C.dim, fontFamily:mono, fontSize:11, fontWeight:700, padding:"9px 22px", cursor:"pointer", transition:"all 0.18s" }),
  delBtn2:   { background:"none", border:`1px solid ${C.red}66`, borderRadius:6, color:C.red, fontFamily:mono, fontSize:9, padding:"5px 12px", cursor:"pointer", opacity:0.7, transition:"all 0.18s" },
};

export { C, S, mono, sans };